In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('/content/Advertising.csv')

In [3]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [10]:
x = df['TV'].values.reshape(-1,1)
y = df['Sales'].values.reshape(-1,1)

In [31]:
x

array([[230.1],
       [ 37.8],
       [ 44.5],
       [ 39.3],
       [ 17.2],
       [ 45.9],
       [151.5],
       [ 41.3],
       [180.8],
       [ 10.8],
       [  8.7],
       [ 48.9],
       [ 57.5],
       [ 32.8],
       [120.2],
       [ 19.6],
       [  8.6],
       [  2.1],
       [199.8],
       [  2.6],
       [ 66.1],
       [  5.8],
       [214.7],
       [ 24. ],
       [ 23.8],
       [ 35.1],
       [ 97.5],
       [  7.6],
       [204.1],
       [ 32.9],
       [195.4],
       [ 47.7],
       [ 67.8],
       [ 36.6],
       [281.4],
       [ 39.6],
       [ 69.2],
       [ 20.5],
       [147.3],
       [ 23.9],
       [218.4],
       [ 27.7],
       [237.4],
       [  5.1],
       [ 13.2],
       [ 15.9],
       [228.3],
       [ 16.9],
       [ 62.3],
       [ 12.6],
       [262.9],
       [  3.5],
       [142.9],
       [ 29.3],
       [240.1],
       [ 16.7],
       [248.8],
       [ 27.1],
       [ 70.6],
       [ 16. ],
       [292.9],
       [ 28.3],
       [

In [12]:
y

array([[22.1],
       [10.4],
       [12. ],
       [16.5],
       [17.9],
       [ 7.2],
       [11.8],
       [13.2],
       [ 4.8],
       [15.6],
       [12.6],
       [17.4],
       [ 9.2],
       [13.7],
       [19. ],
       [22.4],
       [12.5],
       [24.4],
       [11.3],
       [14.6],
       [18. ],
       [17.5],
       [ 5.6],
       [20.5],
       [ 9.7],
       [17. ],
       [15. ],
       [20.9],
       [18.9],
       [10.5],
       [21.4],
       [11.9],
       [13.2],
       [17.4],
       [11.9],
       [17.8],
       [25.4],
       [14.7],
       [10.1],
       [21.5],
       [16.6],
       [17.1],
       [20.7],
       [17.9],
       [ 8.5],
       [16.1],
       [10.6],
       [23.2],
       [19.8],
       [ 9.7],
       [16.4],
       [10.7],
       [22.6],
       [21.2],
       [20.2],
       [23.7],
       [ 5.5],
       [13.2],
       [23.8],
       [18.4],
       [ 8.1],
       [24.2],
       [20.7],
       [14. ],
       [16. ],
       [11.3],
       [11

In [35]:
lin = LinearRegression()

In [39]:
lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
print(lin.intercept_)
print(lin.coef_)

[4.63087946]
[[0.05444896 0.10717457]]


In [41]:
y
Pred_y = lin.predict(x)

In [42]:
np.concatenate((y, Pred_y), axis = 1)

array([[22.1       , 21.21078412],
       [10.4       , 11.26581887],
       [12.        , 10.48671441],
       [16.5       , 17.30620681],
       [17.9       , 15.63273693],
       [ 7.2       , 10.34542196],
       [11.8       , 11.27702065],
       [13.2       , 13.27626614],
       [ 4.8       ,  5.32420713],
       [15.6       , 15.7884357 ],
       [12.6       ,  8.85156828],
       [17.4       , 18.89326105],
       [ 9.2       ,  9.68859218],
       [13.7       , 10.75417988],
       [19.        , 19.26995575],
       [22.4       , 20.38243344],
       [12.5       , 12.24510831],
       [24.4       , 24.19693004],
       [11.3       , 10.59582626],
       [14.6       , 15.21268363],
       [18.        , 19.49126811],
       [17.5       , 18.10365306],
       [ 5.6       ,  7.05368143],
       [20.5       , 18.87282745],
       [ 9.7       ,  9.37344932],
       [17.        , 19.32062224],
       [15.        , 15.55185089],
       [20.9       , 19.49389028],
       [18.9       ,

In [43]:
y - Pred_y

array([[ 8.89215875e-01],
       [-8.65818870e-01],
       [ 1.51328559e+00],
       [-8.06206811e-01],
       [ 2.26726307e+00],
       [-3.14542196e+00],
       [ 5.22979354e-01],
       [-7.62661422e-02],
       [-5.24207126e-01],
       [-1.88435704e-01],
       [ 3.74843172e+00],
       [-1.49326105e+00],
       [-4.88592183e-01],
       [ 2.94582012e+00],
       [-2.69955746e-01],
       [ 2.01756656e+00],
       [ 2.54891687e-01],
       [ 2.03069961e-01],
       [ 7.04173741e-01],
       [-6.12683635e-01],
       [-1.49126811e+00],
       [-6.03653056e-01],
       [-1.45368143e+00],
       [ 1.62717255e+00],
       [ 3.26550684e-01],
       [-2.32062224e+00],
       [-5.51850893e-01],
       [ 1.40610972e+00],
       [-2.18221178e+00],
       [ 3.10230767e-01],
       [-2.21202043e+00],
       [-7.43004672e-01],
       [ 3.11591970e+00],
       [-3.83601486e+00],
       [ 1.90831059e+00],
       [-3.09860809e+00],
       [ 1.54244669e+00],
       [ 7.07359345e-01],
       [ 2.6

In [21]:
np.abs(y - Pred_y).mean()

1.8305872641932412

In [22]:
from sklearn import metrics

In [23]:
metrics.mean_absolute_error(y,Pred_y)

1.8305872641932412

In [24]:
metrics.mean_squared_error(y,Pred_y)

5.2177438977951285

In [25]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [27]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [37]:
x = df[['TV', 'Radio']].values

In [47]:
np.concatenate((y, Pred_y), axis = 1)

array([[22.1       , 21.21078412],
       [10.4       , 11.26581887],
       [12.        , 10.48671441],
       [16.5       , 17.30620681],
       [17.9       , 15.63273693],
       [ 7.2       , 10.34542196],
       [11.8       , 11.27702065],
       [13.2       , 13.27626614],
       [ 4.8       ,  5.32420713],
       [15.6       , 15.7884357 ],
       [12.6       ,  8.85156828],
       [17.4       , 18.89326105],
       [ 9.2       ,  9.68859218],
       [13.7       , 10.75417988],
       [19.        , 19.26995575],
       [22.4       , 20.38243344],
       [12.5       , 12.24510831],
       [24.4       , 24.19693004],
       [11.3       , 10.59582626],
       [14.6       , 15.21268363],
       [18.        , 19.49126811],
       [17.5       , 18.10365306],
       [ 5.6       ,  7.05368143],
       [20.5       , 18.87282745],
       [ 9.7       ,  9.37344932],
       [17.        , 19.32062224],
       [15.        , 15.55185089],
       [20.9       , 19.49389028],
       [18.9       ,

In [44]:
np.abs(y - Pred_y).mean()

1.2367636706717362

In [45]:
metrics.mean_squared_error(y,Pred_y)

2.7060525778834887

In [48]:
#Radio part