In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
df = pd.read_csv('/content/drive/My Drive/Oyesters-ML/HW.csv')
df

ENGINESIZE  CO2EMISSIONS
0         2.0           196
1         2.4           221
2         1.5           136
3         3.5           255
4         3.5           244
5         3.5           230
6         3.5           232
7         3.7           255
8         3.7           267

In [12]:
real_x = df.iloc[:,0].values
real_y = df.iloc[:,1].values
real_x = real_x.reshape(-1,1)
real_y = real_y.reshape(-1,1)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
training_x, testing_x, training_y, testing_y  = train_test_split(real_x, real_y)

In [14]:
Lin = LinearRegression()

In [16]:
Lin.fit(real_x,real_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
Pred_y = Lin.predict(real_x)

In [18]:
Pred_y

array([[180.77160494],
       [198.36539227],
       [158.77937077],
       [246.74830745],
       [246.74830745],
       [246.74830745],
       [246.74830745],
       [255.54520112],
       [255.54520112]])

In [19]:
real_y

array([[196],
       [221],
       [136],
       [255],
       [244],
       [230],
       [232],
       [255],
       [267]])

In [20]:
Pred_y[0]

array([180.77160494])

In [21]:
real_x[0]

array([2.])

In [22]:
real_y[0]

array([196])

In [34]:
Lin.predict([[2.4]])

array([[198.36539227]])

In [25]:
np.concatenate((real_y, Pred_y), axis = 1)

array([[196.        , 180.77160494],
       [221.        , 198.36539227],
       [136.        , 158.77937077],
       [255.        , 246.74830745],
       [244.        , 246.74830745],
       [230.        , 246.74830745],
       [232.        , 246.74830745],
       [255.        , 255.54520112],
       [267.        , 255.54520112]])

In [26]:
real_y - Pred_y

array([[ 15.22839506],
       [ 22.63460773],
       [-22.77937077],
       [  8.25169255],
       [ -2.74830745],
       [-16.74830745],
       [-14.74830745],
       [ -0.54520112],
       [ 11.45479888]])

In [27]:
np.abs(real_y - Pred_y)

array([[15.22839506],
       [22.63460773],
       [22.77937077],
       [ 8.25169255],
       [ 2.74830745],
       [16.74830745],
       [14.74830745],
       [ 0.54520112],
       [11.45479888]])

In [28]:
np.abs(real_y - Pred_y).mean()

12.793220938979601

In [29]:
from sklearn import metrics

In [31]:
#MAE
metrics.mean_absolute_error(real_y, Pred_y)

12.793220938979601

In [33]:
#MSE
metrics.mean_squared_error(real_y, Pred_y)

218.7000973494403