In [1]:
import numpy as np

In [2]:
import pandas as pd
import matplotlib.pyplot as plt


In [11]:
df = pd.read_csv('/content/drive/My Drive/ML Insternship/tissue.csv')
df

x1  x2     y
0   7   7   bad
1   7   4   bad
2   3   4  good
3   1   4  good

In [13]:
x = df.iloc[:, 0:2].values
x

array([[7, 7],
       [7, 4],
       [3, 4],
       [1, 4]])

In [15]:
y = df.iloc[:, 2].values
y

array(['bad', 'bad', 'good', 'good'], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 1, 1])

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

In [19]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [20]:
pred_y = classifier.predict(x)

In [21]:
pred_y

array([0, 0, 1, 1])

In [22]:
y

array([0, 0, 1, 1])

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [24]:
cm = confusion_matrix(y,pred_y)
cm

array([[2, 0],
       [0, 2]])

In [25]:
acc = accuracy_score(y,pred_y)*100

In [26]:
acc

100.0

In [27]:
x_new = np.array([[3, 7]])

In [28]:
prediction = classifier.predict(x_new)
prediction

array([1])

In [29]:
x_new = np.array([[4, 7]])

In [30]:
prediction = classifier.predict(x_new)
prediction

array([0])